server:
  port: 9899

spring:
  liquibase:
    change-log: classpath:db.liquibase/master_liquibase.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: admin
    password: my-password
    driver-class-name: org.postgresql.Driver

  application:
    name: ACCOUNT-SERVICE

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
